=== masao/public_html/etc/wikiwiki-cmp.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- $Id$ -->
<!--************************************-->
<!--                  DTD               -->
<!--************************************-->

<!ELEMENT wikiwiki-cmp (engine*)>

<!ELEMENT engine (description,
		  implementation,
		  backend,
		  japanese,
		  history,
		  changelog,
		  acl,
		  notify,
		  upload,
		  table,
		  html,
		  interwikiname,
		  link-in-page,
		  plugin
		  )>

<!ELEMENT link (#PCDATA)>

<!ELEMENT description (#PCDATA|link)*>
<!ELEMENT backend (#PCDATA|link)*>
<!ELEMENT implementation (#PCDATA|link)*>
<!ELEMENT japanese (#PCDATA|link)*>
<!ELEMENT history (#PCDATA|link)*>
<!ELEMENT changelog (#PCDATA|link)*>
<!ELEMENT interwikiname (#PCDATA|link)*>
<!ELEMENT link-in-page (#PCDATA|link)*>
<!ELEMENT table (#PCDATA|link)*>
<!ELEMENT html (#PCDATA|link)*>
<!ELEMENT upload (#PCDATA|link)*>
<!ELEMENT acl (#PCDATA|link)*>
<!ELEMENT notify (#PCDATA|link)*>
<!ELEMENT plugin (#PCDATA|link)*>

<!ATTLIST engine id ID #REQUIRED
		 title CDATA #REQUIRED
		 href CDATA #REQUIRED>

<!ATTLIST link title CDATA #IMPLIED
	       href CDATA #REQUIRED>

<!ATTLIST implementation label CDATA #REQUIRED>
<!ATTLIST backend label CDATA #REQUIRED>
<!ATTLIST japanese label CDATA #REQUIRED>
<!ATTLIST history label CDATA #REQUIRED>
<!ATTLIST changelog label CDATA #REQUIRED>
<!ATTLIST interwikiname label CDATA #REQUIRED>
<!ATTLIST link-in-page label CDATA #REQUIRED>
<!ATTLIST table label CDATA #REQUIRED>
<!ATTLIST html label CDATA #REQUIRED>
<!ATTLIST upload label CDATA #REQUIRED>
<!ATTLIST acl label CDATA #REQUIRED>
<!ATTLIST notify label CDATA #REQUIRED>
<!ATTLIST plugin label CDATA #REQUIRED>

=== masao/public_html/etc/wikiwiki-cmp.xml
<?xml version="1.0" encoding="EUC-JP"?>
<!DOCTYPE wikiwiki-cmp SYSTEM "wikiwiki-cmp.dtd">
<wikiwiki-cmp>
<!--
  <engine id="tiki" title="Tiki">
    <implementation label="Ruby"></implementation>
    <japanese label="〇○"></japanese>
    <history label="○"></history>
    <interwikiname label="a"></interwikiname>
    <link-in-page label="a"></link-in-page>
    <table label="a"></table>
    <html label="a"></html>
    <upload label="a"></upload>
    <acl label="a"></acl>
    <notify label="a"></notify>
    <plugin label="a"></plugin>
  </engine>  
-->
  <engine id="yukiwiki" title="YukiWiki" href="http://www.hyuki.com/yukiwiki/">
    <description>
	日本語対応としては、初期に公開されたWikiEngineの一つ。
	YukiWikiを参考にした派生版のWikiEngineも数多く作られている。
    </description>
    <implementation label="Perl"></implementation>
    <backend label="DBM"></backend>
    <japanese label="○">WikiNameを作るには[[日本語]]とする。</japanese>
    <history label="○">過去一回の履歴を保持している。（差分表示機能）</history>
    <changelog label="×"></changelog>
    <acl label="△">管理者による凍結機能あり</acl>
    <notify label="○"></notify>
    <upload label="×"></upload>
    <table label="○">,を行頭に置く</table>
    <html label="×"></html>
    <interwikiname label="○"><link href="http://www.hyuki.com/yukiwiki/wiki.cgi?InterWiki%A5%C6%A5%AF%A5%CB%A5%AB%A5%EB">InterWikiNameテクニカル</link></interwikiname>
    <link-in-page label="○">見出しを使った目次生成機能のみ</link-in-page>
    <plugin label="×"></plugin>
  </engine>

  <engine id="pukiwiki" title="PukiWiki" href="http://pukiwiki.org/">
    <description>
	元々は、YukiWikiの機能をPHPに移植したものだが、
        プラグインによる拡張も進み、現在では機能的には本家を上回っている。
    </description>
    <implementation label="PHP"></implementation>
    <backend label="ファイル"></backend>
    <japanese label="○">WikiNameの定義は[[WikiName]]という形式で行う。</japanese>
    <history label="○">バックアップ機能として実装</history>
    <changelog label="×"></changelog>
    <acl label="△">
	管理者によるページ凍結機能あり。
	<link href="http://www.pukiwiki.org/index.php?%5B%5B%BC%C1%CC%E4%C8%A2%5D%5D#content:32">アクセス制限について</link>
    </acl>
    <notify label="×">
	<link href="http://www.pukiwiki.org/index.php?%5B%5BBugTrack%2F111%5D%5D">BugTrack/111</link>
    </notify>
    <upload label="○">添付ファイル機能</upload>
    <table label="○"><link href="http://www.pukiwiki.org/index.php?%5B%5B%A5%D8%A5%EB%A5%D7%5D%5D#content:12">表組み</link></table>
    <html label="○">プラグインでの実装</html>
    <interwikiname label="○">InterWikiNameページにリストを追加するだけで簡単に定義できる。<link href="http://www.pukiwiki.org/index.php?%5B%5BInterWiki%A5%C6%A5%AF%A5%CB%A5%AB%A5%EB%5D%5D">InterWikiNameテクニカル</link></interwikiname>
    <link-in-page label="○">見出しを参照して目次を付ける機能のみ</link-in-page>
    <plugin label="○">
	たくさんある。
	<link href="http://www.pukiwiki.org/index.php?%5B%5B%A5%D7%A5%E9%A5%B0%A5%A4%A5%F3%5D%5D">プラグイン</link>
    </plugin>
  </engine>

  <engine id="rwiki" title="RWiki" href="http://rwiki.jin.gr.jp/cgi-bin/rw-cgi.rb?cmd=view;name=top">
    <description>
	dRubyによる分散オブジェクトの実装例として作成されたため、
	*いわゆる*WikiCloneの実装とは設計思想が異なる。
	書式はRD形式という独自の文書形式を使い、
	WikiNameによる参照は行わない。
    </description>
    <implementation label="Ruby"></implementation>
    <backend label="ファイル"></backend>
    <japanese label="○">((&lt;日本語&gt;))という形式で参照する</japanese>
    <history label="×"></history>
    <changelog label="×"></changelog>
    <acl label="×"></acl>
    <notify label="○"></notify>
    <upload label="×"></upload>
    <table label="×"></table>
    <html label="×">RD形式なので…。</html>
    <interwikiname label="×">
	参照の記述がRD形式なので、WikiNameの機構そのものを持たない…。
    </interwikiname>
    <link-in-page label="×"></link-in-page>
    <plugin label="○"></plugin>
  </engine>

  <engine id="moinmoin" title="MoinMoin" href="http://www.gembook.jp/html/moin/moin.cgi/FrontPage">
    <description>
	Pythonで書かれた海外で作られている実装。
	Python自体が、*日本では*マイナーなので、あまり使われていない模様…。
	<link href="http://moin.sourceforge.net/">本家サイト</link>
    </description>
    <implementation label="Python"></implementation>
    <backend label="ファイル"></backend>
    <japanese label="○">WikiNameは["日本語"]の形式</japanese>
    <history label="○">全履歴および差分を参照可</history>
    <changelog label="×"></changelog>
    <acl label="×"><link href="http://purl.org/wiki/moin/PasswordProtectedEditing">PasswordProtectedEditing</link></acl>
    <notify label="○"></notify>
    <upload label="○"></upload>
    <table label="○"><link href="http://purl.net/wiki/moin/HelpOnTables"></link></table>
    <html label="○"><link href="http://purl.net/wiki/moin/HelpMiscellaneous_2fFrequentlyAskedQuestions#head-76e09d14a9f98113ce8a9fbbce0435c8eba4cab5">Can I add HTML to the wiki?</link></html>
    <interwikiname label="○"></interwikiname>
    <link-in-page label="○"></link-in-page>
    <plugin label="○"></plugin>
  </engine>

  <engine id="usemod" title="UseModWiki" href="http://www.usemod.com/cgi-bin/wiki.pl?UseModWiki">
    <description>
	EmacsWiki.orgが採用するなど、海外では結構人気があるみたい。
	日本語はそのままでは通らない（日本語対応パッチあり）。
    </description>
    <implementation label="Perl"></implementation>
    <backend label="ファイル"></backend>
    <japanese label="×"><link href="http://p5ee.net/wiki.pl?WikiName">p5ee:WikiName</link></japanese>
    <history label="○">全履歴および差分を参照可</history>
    <changelog label="○"></changelog>
    <acl label=""></acl>
    <notify label=""></notify>
    <table label=""></table>
    <html label=""></html>
    <upload label=""></upload>
    <interwikiname label="○"></interwikiname>
    <link-in-page label=""></link-in-page>
    <plugin label=""></plugin>
  </engine>
</wikiwiki-cmp>
